### ISSUE TITLE
Undo hibernate

### ISSUE THREAD

**Issue by lubert** [lightrush/framework-laptop-formula#19]
Hey, thanks for creating and maintaining this project! Is it possible to undo the hibernate step? I applied it, but for whatever reason my Framework laptop no longer goes to sleep when I close the lid, so I'm wondering if there's a way to undo it.

**Comment by lightrush** [comment]
Yes, it is. You could undo the changes done by `hibernate.sls`. Or I could write a cleanup state that automates that. :D I assume you figured it out since you closed this?

**Comment by lubert** [comment]
Turns out the issue for me was that "Secure Boot" was enabled in the BIOS. After turning off, hibernation now works 👍

**Comment by lightrush** [comment]
Interesting. We should probably put that in the README.md.
