### ISSUE TITLE
document how to find status of current available states? dry-run? test?

### ISSUE THREAD

**Issue by rkiddy** [lightrush/framework-laptop-formula#21]
I am not expert at salt here, but I wanted to find out what is what. I am applying (some of) the states indivudually.
I have looked at some of the salt documentation and, yes, a little knowledge is a dangerous thing. But you should be able to see below, I applied one state and it failed and another and it succeeded. Now I would like to see a list of the states and what succeeded, what failed, what has not been run yet, and such as test. I would also like to be able to dry-run the state.apply commands, but it is not clear how or if that can be done.

Any suggestions here?

    $ git clone git@github.com:lightrush/framework-laptop-formula.git
    $ cd framework-laptop
    $
    $ sudo bash
    #
    # salt-call -l error --local --file-root="$(pwd)" state.test
     local:
     ----------
               ID: states
         Function: no.None
           Result: False
          Comment: No Top file or master_tops data matches found. Please see master log for details.
          Changes:   
     
     Summary for local
     ------------
     Succeeded: 0
     Failed:    1
     ------------
     Total states run:     1
     Total run time:   0.000 ms
     # 
     # salt-call -l error --local --file-root="$(pwd)" state.apply intel-audio-workaround
     [ERROR   ] Source file salt://framework-laptop/files/intel-audio-workaround.conf not found in saltenv 'base'
     local:
     ----------
               ID: intel_audio_workaround_modprobe_conf_installed
         Function: file.managed
             Name: /etc/modprobe.d/intel-audio-workaround.conf
           Result: False
          Comment: Source file salt://framework-laptop/files/intel-audio-workaround.conf not found in saltenv 'base'
          Started: 13:13:59.507277
         Duration: 802.34 ms
          Changes:   
     ----------
               ID: intel_audio_workaround_initramfs_updated
         Function: cmd.run
             Name: update-initramfs -u
           Result: False
          Comment: One or more requisite failed: intel-audio-workaround.intel_audio_workaround_modprobe_conf_installed
          Started: 13:14:00.309935
         Duration: 0.003 ms
          Changes:   
     
     Summary for local
     ------------
     Succeeded: 0
     Failed:    2
     ------------
     Total states run:     2
     Total run time: 802.343 ms
     root@ray0:/home/ray/Projects/framework-laptop-formula/framework-laptop# salt-call -l error --local --file-root="$(pwd)" state.apply tlp
     local:
     ----------
               ID: tlp_package_installed
         Function: pkg.installed
             Name: tlp
           Result: True
          Comment: The following packages were installed/updated: tlp
          Started: 13:15:15.960058
         Duration: 10151.787 ms
          Changes:   
                   ----------
                   ethtool:
                       ----------
                       new:
                           1:5.4-1
                       old:
                   tlp:
                       ----------
                       new:
                           1.3.1-2
                       old:
                   tlp-rdw:
                       ----------
                       new:
                           1.3.1-2
                       old:
     ----------
               ID: tlp_service_running
         Function: service.running
             Name: tlp
           Result: True
          Comment: Service tlp is already enabled, and is running
          Started: 13:15:26.120020
         Duration: 426.251 ms
          Changes:   
                   ----------
                   tlp:
                       True
     
     Summary for local
     ------------
     Succeeded: 2 (changed=2)
     Failed:    0
     ------------
     Total states run:     2
     Total run time:  10.578 s
     # 
     # salt-call -l error --local --file-root="$(pwd)" state.test
     local:
     ----------
               ID: states
         Function: no.None
           Result: False
          Comment: No Top file or master_tops data matches found. Please see master log for details.
          Changes:   
     
     Summary for local
     ------------
     Succeeded: 0
     Failed:    1
     ------------
     Total states run:     1
     Total run time:   0.000 ms
     # 
     # salt-call -l error --local --file-root="$(pwd)" state.list_disabled
     local:
     # 
     # salt-call -l error --local --file-root="$(pwd)" state.highstate test
     local:
     ----------
               ID: states
         Function: no.None
           Result: False
          Comment: No Top file or master_tops data matches found. Please see master log for details.
          Changes:   
     
     Summary for local
     ------------
     Succeeded: 0
     Failed:    1
     ------------
     Total states run:     1
     Total run time:   0.000 ms
     # 
     # salt-call -l error --local --file-root="$(pwd)" state.sls test
     local:
         Data failed to compile:
     ----------
         No matching sls found for 'test' in env 'base'
     # 
     # salt-call -l error --local --file-root="$(pwd)" state.list_enabled
     'state.list_enabled' is not available.
     # 
     # salt-call -l error --local --file-root="$(pwd)" state.check_request
     local:
     
     Summary for local
     -----------
     Succeeded: 0
     Failed:   0
     -----------
     Total states run:    0
     Total run time:  0.000 ms
     # 
     # salt-call -l error --local --file-root="$(pwd)" state.apply test
     local:
         Data failed to compile:
     ----------
         No matching sls found for 'test' in env 'base'
     # 
     # exit

**Comment by lightrush** [comment]
1. You have to make sure you're running the formula from the right location. `--file-root="SOMEWHERE"` needs to point to the location where the state you're calling is found. If you're calling `framework-laptop` or any child state `framework-laptop.tlp` the state needs to exist in that path. So if we want to call `framework-laptop`, `--file-root="SOMEWHERE"` has to point to the directory containing the `framework-laptop` dir. When you try to call individual child states, you have entered the `framework-laptop` dir and given *that* as --file-root which naively makes sense. Unfortunately many states require additional files and reference them via the parent state. E.g. `salt://framework-laptop/files/something`. If your --file-root is `framework-lapop`, that path is invalid and the states fail. Instead call individual states like so `framework-laptop.tlp` and keep  the --file-root as the directory containing `framework-laptop`.
2. Salt doesn't keep what states succeeded and what failed somewhere centrally. salt-call is a transient operation. Once it exits, it's over. States should be idempotent and therefore should be applicable repeatedly. For that reason you should have no issues just calling `state.apply` again if you want to check what failed and what succeeded, if you lost the previous command output. 
3. Dry run is easy and useful: `salt-call ... test=True`

**Comment by lightrush** [comment]
More on `state.apply` - https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.state.html#salt.modules.state.apply_.

**Comment by rkiddy** [comment]
This answers my questions. Much thanx
