### ISSUE TITLE
Support for Pop!_OS? 

### ISSUE THREAD

**Issue by shombando** [lightrush/framework-laptop-formula#37]
Hi @lightrush, thanks for sharing your excellent work. I'm using it on Pop!_OS 22.04 now. Salt-bootstrap didn't have support for Pop!_OS but my [PR just got merged](https://github.com/saltstack/salt-bootstrap/pull/1888). 

Pop!_OS uses sytemd-boot instead of grub so the following equivalents were needed:

```
➜ sudo kernelstub -a "mem_sleep_default=deep"
➜ sudo kernelstub -a "nvme.noacpi=1"
```

Would you be interested in adding support for Pop!_OS? If so, I can try to learn Salt a bit more and propose a PR. 

Thanks again for this super helpful repo and introducing me to Salt.

**Comment by lightrush** [comment]
Hey Shom, currently I don't have the bandwidth to create the change so you're welcome to making it yourself. I'll help getting it in shape. Don't have to learn too much Salt unless you want to. You probably want to write a reversible method that adds a parameter to the kernel boot command line. Then that can be switched either on the OS name or probably better, if it's detected that systemd-boot is used. That way it'll work for other systemd-boot OSes without modification.

**Comment by shombando** [comment]
@lightrush thanks for the feedback, I'll try to pick this up after the holidays. Once I have a start, I'll open a draft PR and get your help to get it into shape. Thanks for suggesting the approach as well, I'll follow that.

**Comment by shombando** [comment]
@lightrush the situation has changed a lot, I'm moving towards a NixOS setup on AMD mainboard. Thanks for all the help, closing the issue.
